import os
import json
from supabase import create_client, Client
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
DATABASE_URL = os.getenv("DATABASE_URL") # Try to get direct DB connection

if not SUPABASE_URL or not SUPABASE_KEY:
    print("Error: SUPABASE_URL and SUPABASE_KEY must be set in .env file")
    exit(1)

supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

TABLE_NAME = "site_pages_content"

sql_command = f"""
-- Create the Unified Content Table
CREATE TABLE IF NOT EXISTS {TABLE_NAME} (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_slug TEXT NOT NULL,
    section_key TEXT NOT NULL,
    content JSONB DEFAULT '{{}}'::jsonb,
    order_index INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Ensure unique combination of page and section
    CONSTRAINT unique_page_section UNIQUE (page_slug, section_key)
);

-- Optional: Create an index for faster lookups by page
CREATE INDEX IF NOT EXISTS idx_page_slug ON {TABLE_NAME} (page_slug);

-- Enable RLS
ALTER TABLE {TABLE_NAME} ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON {TABLE_NAME} FOR SELECT USING (true);
CREATE POLICY "Public write access" ON {TABLE_NAME} FOR ALL USING (true); -- Note: Secure this in production!
"""

def attempt_auto_create():
    if not DATABASE_URL:
        return False, "DATABASE_URL not found in .env"
    
    try:
        import psycopg2
        print(f"INFO: Attempting to connect directly to database using DATABASE_URL...")
        conn = psycopg2.connect(DATABASE_URL)
        cur = conn.cursor()
        print(f"INFO: Executing SQL to create table '{TABLE_NAME}'...")
        cur.execute(sql_command)
        conn.commit()
        cur.close()
        conn.close()
        return True, "Success"
    except Exception as e:
        return False, str(e)

print(f"--- Supabase Setup for '{TABLE_NAME}' ---")

# Try auto-create first
auto_created, msg = attempt_auto_create()

if auto_created:
    print(f"SUCCESS: Table '{TABLE_NAME}' created automatically.")
else:
    print(f"NOTICE: Could not auto-create table ({msg}).")
    print("Please run the following SQL manually in Supabase SQL Editor:\n")
    print(sql_command)
    print("\n-------------------------------------------")

# Helper to verify connection
try:
    print("Verifying Supabase connection...")
    res = supabase.table(TABLE_NAME).select("count", count="exact").execute()
    print(f"Connection successful. Table '{TABLE_NAME}' exists with {res.count} rows.")
except Exception as e:
    print(f"Note: Table '{TABLE_NAME}' verification failed (it likely doesn't exist yet via API).")


